# Generated by Django 5.0 on 2024-05-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("omni_pro_oms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operation",
            name="http_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("GET", "GET"),
                    ("POST", "POST"),
                    ("PUT", "PUT"),
                    ("DELETE", "DELETE"),
                    ("PATCH", "PATCH"),
                    ("OPTIONS", "OPTIONS"),
                    ("HEAD", "HEAD"),
                    ("CONNECT", "CONNECT"),
                    ("TRACE", "TRACE"),
                ],
                max_length=255,
                null=True,
                verbose_name="HTTP Method",
            ),
        ),
    ]
