# Generated by Django 5.0 on 2024-02-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("omni_pro_oms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operation",
            name="auth_type",
            field=models.CharField(
                help_text="Basic, Bearer, etc.",
                max_length=255,
                verbose_name="Auth Type",
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="http_method",
            field=models.CharField(
                choices=[
                    ("GET", "GET"),
                    ("POST", "POST"),
                    ("PUT", "PUT"),
                    ("DELETE", "DELETE"),
                    ("PATCH", "PATCH"),
                    ("OPTIONS", "OPTIONS"),
                    ("HEAD", "HEAD"),
                    ("CONNECT", "CONNECT"),
                    ("TRACE", "TRACE"),
                ],
                max_length=255,
                verbose_name="HTTP Method",
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="score",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                help_text="Level of priority",
                max_length=255,
                verbose_name="Score",
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="timeout",
            field=models.IntegerField(help_text="In seconds", verbose_name="Timeout"),
        ),
    ]
