# Generated by Django 5.0 on 2024-05-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omni_pro_oms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='item',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Item'),
        ),
    ]
