# Generated by Django 5.0 on 2024-06-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omni_pro_oms', '0002_task_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Token'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Token Expires At'),
        ),
    ]
