# Generated by Django 5.0 on 2024-06-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omni_pro_oms', '0002_task_item_tenant_token_tenant_token_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='token',
            field=models.TextField(blank=True, null=True, verbose_name='Token'),
        ),
    ]
