# Generated by Django 5.0 on 2024-02-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("omni_pro_oms", "0002_alter_operation_auth_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operation",
            name="auth_type",
            field=models.CharField(
                help_text="OAUTH, Bearer, etc.",
                max_length=255,
                verbose_name="Auth Type",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="body_dst",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Body Destination"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="body_src",
            field=models.JSONField(blank=True, null=True, verbose_name="Body Source"),
        ),
        migrations.AlterField(
            model_name="task",
            name="headers_dst",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Headers Destination"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="headers_src",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Headers Source"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="params_dst",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Params Destination"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="params_src",
            field=models.JSONField(blank=True, null=True, verbose_name="Params Source"),
        ),
        migrations.AlterField(
            model_name="task",
            name="response_dst",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Response Destination"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="response_src",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Response Source"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="time",
            field=models.IntegerField(
                blank=True, help_text="In milliseconds", null=True, verbose_name="Time"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="url_dst",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="URL Destination"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="url_src",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="URL Source"
            ),
        ),
    ]
