# Generated by Django 5.0 on 2024-06-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("omni_pro_oms", "0003_alter_tenant_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="operation",
            name="other_clean_task_days",
            field=models.IntegerField(
                blank=True,
                help_text="In days",
                null=True,
                verbose_name="Other Clean Task Days",
            ),
        ),
        migrations.AddField(
            model_name="operation",
            name="packages_to_clean_count",
            field=models.IntegerField(
                blank=True,
                help_text="Number of packages to clean",
                null=True,
                verbose_name="Packages To Clean Count",
            ),
        ),
        migrations.AddField(
            model_name="operation",
            name="success_clean_task_days",
            field=models.IntegerField(
                blank=True,
                help_text="In days",
                null=True,
                verbose_name="Success Clean Task Days",
            ),
        ),
    ]
