# Generated by Django 5.0 on 2024-03-18 16:43

import django.db.models.deletion
import omni_pro_oms.models.config
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omni_pro_oms', '0003_alter_operation_auth_type_alter_task_body_dst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tenant_operation_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='omni_pro_oms.tenantoperation', verbose_name='TenantOperation'),
        ),
        migrations.AlterField(
            model_name='config',
            name='auth',
            field=models.JSONField(blank=True, default=omni_pro_oms.models.config.get_default_auth, null=True, verbose_name='Auth'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='auth_type',
            field=models.CharField(choices=[('token', 'Token'), ('bearer_token', 'Bearer Token'), ('api_key', 'Api Key'), ('auth2', 'Auth2'), ('auth1', 'Auth1')], max_length=255, verbose_name='Auth Type'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('error', 'Error'), ('success', 'Success'), ('partial_success', 'Partial Success')], default='waiting', max_length=256, verbose_name='Status'),
        ),
    ]
