# Generated by Django 5.0 on 2024-12-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("omni_pro_oms", "0004_operation_other_clean_task_days_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="celery_task_id",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Celery Task ID"
            ),
        ),
    ]
