# Generated by Django 5.0 on 2024-12-03 21:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("omni_pro_oms", "0004_operation_other_clean_task_days_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="operation",
            name="picking_state",
            field=models.BooleanField(
                default=False,
                help_text="If the operation is in picking state",
                verbose_name="Picking State",
            ),
        ),
    ]
