# Generated by Django 5.0 on 2024-03-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omni_pro_oms', '0004_task_tenant_operation_id_alter_config_auth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationtype',
            name='code',
        ),
        migrations.AddField(
            model_name='operationtype',
            name='operation_code',
            field=models.CharField(choices=[('default', 'Select an option')], default='default', max_length=255, verbose_name='Operation Code'),
        ),
    ]
