# Generated by Django 5.0 on 2024-03-19 22:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("omni_pro_oms", "0005_remove_operationtype_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operationtype",
            name="operation_code",
            field=models.CharField(
                default="default", max_length=255, verbose_name="Operation Code"
            ),
        ),
    ]
