# Generated by Django 5.0 on 2024-04-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("omni_pro_oms", "0006_alter_operationtype_operation_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operation",
            name="auth_type",
            field=models.CharField(
                choices=[
                    ("token", "Token"),
                    ("bearer_token", "Bearer Token"),
                    ("api_key", "Api Key"),
                    ("auth2", "Auth2"),
                    ("auth1", "Auth1"),
                    ("custom", "Custom"),
                ],
                max_length=255,
                verbose_name="Auth Type",
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="http_method",
            field=models.CharField(
                choices=[
                    ("GET", "GET"),
                    ("POST", "POST"),
                    ("PUT", "PUT"),
                    ("DELETE", "DELETE"),
                    ("PATCH", "PATCH"),
                    ("OPTIONS", "OPTIONS"),
                    ("HEAD", "HEAD"),
                    ("CONNECT", "CONNECT"),
                    ("TRACE", "TRACE"),
                ],
                max_length=255,
                null=True,
                verbose_name="HTTP Method",
            ),
        ),
    ]
