# Generated by Django 5.0 on 2025-03-19 16:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omni_pro_oms', '0006_task_celery_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='active_notifications',
            field=models.BooleanField(default=False, verbose_name='Active Notifications'),
        ),
        migrations.AddField(
            model_name='operation',
            name='emails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, default=list, size=None, verbose_name='Emails'),
        ),
        migrations.AddField(
            model_name='operation',
            name='status_notifications',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('error', 'Error'), ('success', 'Success'), ('partial_success', 'Partial Success')], default='error', max_length=256, verbose_name='Status Notifications'),
        ),
    ]
