# Generated by Django 5.0 on 2025-05-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "omni_pro_oms",
            "0007_operation_active_notifications_operation_emails_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="expires_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date to token expiration"
            ),
        ),
        migrations.AddField(
            model_name="config",
            name="expires_in",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Time to token expiration"
            ),
        ),
        migrations.AlterField(
            model_name="config",
            name="token",
            field=models.TextField(blank=True, null=True, verbose_name="Token"),
        ),
    ]
